{
  "format_version": 2,
  "sksl": {
    "entrypoint": "grid_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform vec2 uCameraCentre;\nuniform float uZoom;\nuniform float uGridSize;\nuniform float uDotRadius;\nuniform float uMinSpacing;\nuniform vec4 uGridColor;\nuniform vec4 uBgColor;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 screen = FLT_flutter_local_FlutterFragCoord() - (uSize * 0.5);\n    vec2 world = (screen / vec2(uZoom)) + uCameraCentre;\n    float ratio = uMinSpacing / max(uGridSize * uZoom, 9.9999997473787516355514526367188e-05);\n    float step = exp2(max(0.0, ceil(log2(ratio))));\n    float effective = uGridSize * step;\n    vec2 cell = mod(world, vec2(effective));\n    vec2 toNearest = min(cell, vec2(effective) - cell);\n    float dist = length(toNearest) * uZoom;\n    float dot = 1.0 - smoothstep(uDotRadius - 1.0, uDotRadius + 1.0, dist);\n    float strength = dot * uGridColor.w;\n    fragColor = vec4(mix(uBgColor.xyz, uGridColor.xyz, vec3(strength)), uBgColor.w);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uCameraCentre",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uZoom",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uGridSize",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uDotRadius",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uMinSpacing",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "uGridColor",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 7,
        "name": "uBgColor",
        "rows": 4,
        "type": 10
      }
    ]
  }
}