{
  "format_version": 2,
  "sksl": {
    "entrypoint": "ring_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uCentre;\nuniform vec2 uHalf;\nuniform float uRadius;\nuniform float uHalfWidth;\nuniform float uFeather;\nuniform vec4 uColor;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_superellipse(vec2 p, vec2 extent, float radius)\n{\n    float depart = radius * 1.41999995708465576171875;\n    vec2 q = (abs(p) - extent) + vec2(depart);\n    vec2 corner = max(q, vec2(0.0));\n    float curve = pow(pow(corner.x, 3.0499999523162841796875) + pow(corner.y, 3.0499999523162841796875), 0.3278688490390777587890625);\n    return (min(max(q.x, q.y), 0.0) + curve) - depart;\n}\n\nvoid FLT_main()\n{\n    vec2 param = FLT_flutter_local_FlutterFragCoord() - uCentre;\n    vec2 param_1 = uHalf;\n    float param_2 = uRadius;\n    float distance = abs(FLT_flutter_local_superellipse(param, param_1, param_2));\n    float coverage = 1.0 - smoothstep(uHalfWidth - uFeather, uHalfWidth + uFeather, distance);\n    float alpha = uColor.w * coverage;\n    fragColor = vec4(uColor.xyz * alpha, alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uCentre",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uHalf",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uRadius",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uHalfWidth",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uFeather",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uColor",
        "rows": 4,
        "type": 10
      }
    ]
  }
}